using System.Globalization;

namespace CluadeX.Services;

/// <summary>
/// Localization service supporting Thai and English languages.
/// Uses dictionary-based translations with fallback to English.
/// </summary>
public class LocalizationService
{
    private string _currentLanguage = "en";
    public string CurrentLanguage => _currentLanguage;
    public event Action? LanguageChanged;

    // ─── Translation Dictionaries ────────────────────────────────

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        // ═══════ NAVIGATION ═══════
        ["nav.chat"] = new() { ["en"] = "Chat", ["th"] = "แชท" },
        ["nav.models"] = new() { ["en"] = "Models", ["th"] = "โมเดล" },
        ["nav.settings"] = new() { ["en"] = "Settings", ["th"] = "ตั้งค่า" },
        ["nav.plugins"] = new() { ["en"] = "Plugins", ["th"] = "ปลั๊กอิน" },
        ["nav.permissions"] = new() { ["en"] = "Permissions", ["th"] = "สิทธิ์" },
        ["nav.tasks"] = new() { ["en"] = "Tasks", ["th"] = "งาน" },
        ["nav.features"] = new() { ["en"] = "Features", ["th"] = "ฟีเจอร์" },
        ["nav.mcpServers"] = new() { ["en"] = "MCP Servers", ["th"] = "เซิร์ฟเวอร์ MCP" },
        ["mcp.title"] = new() { ["en"] = "MCP Servers", ["th"] = "เซิร์ฟเวอร์ MCP" },
        ["mcp.subtitle"] = new() { ["en"] = "Manage Model Context Protocol servers — add tools and integrations for the AI agent", ["th"] = "จัดการเซิร์ฟเวอร์ MCP — เพิ่มเครื่องมือและการเชื่อมต่อสำหรับ AI agent" },

        // ═══════ SIDEBAR ═══════
        ["sidebar.newChat"] = new() { ["en"] = "New Chat", ["th"] = "แชทใหม่" },
        ["sidebar.openFolder"] = new() { ["en"] = "Open Folder", ["th"] = "เปิดโฟลเดอร์" },
        ["sidebar.chatHistory"] = new() { ["en"] = "CHAT HISTORY", ["th"] = "ประวัติแชท" },
        ["sidebar.noConversations"] = new() { ["en"] = "No conversations yet.\nClick 'New Chat' to start!", ["th"] = "ยังไม่มีการสนทนา\nคลิก 'แชทใหม่' เพื่อเริ่ม!" },
        ["sidebar.noResults"] = new() { ["en"] = "No results found.", ["th"] = "ไม่พบผลลัพธ์" },
        ["sidebar.deleteSession"] = new() { ["en"] = "Delete session", ["th"] = "ลบเซสชัน" },
        ["sidebar.clearSearch"] = new() { ["en"] = "Clear search", ["th"] = "ล้างการค้นหา" },

        // ═══════ TITLEBAR ═══════
        ["title.subtitle"] = new() { ["en"] = " — AI Coding Assistant", ["th"] = " — ผู้ช่วยเขียนโค้ด AI" },

        // ═══════ SETTINGS PAGE ═══════
        ["settings.title"] = new() { ["en"] = "Settings", ["th"] = "ตั้งค่า" },
        ["settings.subtitle"] = new() { ["en"] = "Configure CluadeX preferences and paths", ["th"] = "ตั้งค่าการใช้งาน CluadeX" },
        ["settings.provider"] = new() { ["en"] = "AI Provider", ["th"] = "ผู้ให้บริการ AI" },
        ["settings.activeProvider"] = new() { ["en"] = "Active Provider", ["th"] = "ผู้ให้บริการที่ใช้งาน" },
        ["settings.language"] = new() { ["en"] = "Language / ภาษา", ["th"] = "ภาษา / Language" },
        ["settings.languageDesc"] = new() { ["en"] = "Switch between English and Thai", ["th"] = "สลับระหว่างภาษาอังกฤษและภาษาไทย" },
        ["settings.inference"] = new() { ["en"] = "Inference Settings", ["th"] = "ตั้งค่าการประมวลผล" },
        ["settings.temperature"] = new() { ["en"] = "Temperature", ["th"] = "อุณหภูมิ (Temperature)" },
        ["settings.maxTokens"] = new() { ["en"] = "Max Tokens", ["th"] = "จำนวนโทเค็นสูงสุด" },
        ["settings.contextSize"] = new() { ["en"] = "Context Size", ["th"] = "ขนาด Context" },
        ["settings.agent"] = new() { ["en"] = "Agent Settings", ["th"] = "ตั้งค่า Agent" },
        ["settings.autoExecute"] = new() { ["en"] = "Auto Execute Code", ["th"] = "รันโค้ดอัตโนมัติ" },
        ["settings.directories"] = new() { ["en"] = "Directories", ["th"] = "ไดเรกทอรี" },
        ["settings.saved"] = new() { ["en"] = "Settings saved!", ["th"] = "บันทึกแล้ว!" },
        ["settings.featureToggles"] = new() { ["en"] = "Feature Toggles", ["th"] = "เปิด/ปิดฟีเจอร์" },
        ["settings.featureTogglesDesc"] = new() { ["en"] = "Enable or disable optional features", ["th"] = "เปิดหรือปิดฟีเจอร์เสริม" },

        // Settings page — added for XAML localization via {services:Loc ...}
        ["settings.providerChoose"] = new() { ["en"] = "Choose between local GGUF models, cloud APIs (OpenAI, Anthropic, Gemini), or Ollama", ["th"] = "เลือกระหว่างโมเดล GGUF ในเครื่อง, Cloud API (OpenAI, Anthropic, Gemini) หรือ Ollama" },
        ["settings.localGgufNotice"] = new() { ["en"] = "Using local GGUF models via LLamaSharp. Load models from the Models tab.", ["th"] = "ใช้โมเดล GGUF บนเครื่องผ่าน LLamaSharp โหลดโมเดลจากแท็บ Models" },
        ["settings.apiKey"] = new() { ["en"] = "API Key", ["th"] = "API Key" },
        ["settings.apiKeyDesc"] = new() { ["en"] = "Your API key for this provider. Stored locally in settings.json. Click 'Show' to reveal while editing.", ["th"] = "API Key สำหรับผู้ให้บริการนี้ เก็บไว้ในเครื่องที่ settings.json คลิก 'แสดง' เพื่อดูขณะแก้ไข" },
        ["settings.apiKeyShow"] = new() { ["en"] = "Show", ["th"] = "แสดง" },
        ["settings.apiKeyHide"] = new() { ["en"] = "Hide", ["th"] = "ซ่อน" },
        ["settings.apiKeyToggleTooltip"] = new() { ["en"] = "Show or hide the API key", ["th"] = "แสดงหรือซ่อน API Key" },
        ["settings.baseUrl"] = new() { ["en"] = "Base URL (optional)", ["th"] = "Base URL (ไม่บังคับ)" },
        ["settings.baseUrlDesc"] = new() { ["en"] = "Override for proxies, Azure OpenAI, or custom endpoints. Leave blank for default.", ["th"] = "ใช้สำหรับ proxy, Azure OpenAI หรือ endpoint พิเศษ เว้นว่างเพื่อใช้ค่าเริ่มต้น" },
        ["settings.model"] = new() { ["en"] = "Model", ["th"] = "โมเดล" },
        ["settings.useCustomModel"] = new() { ["en"] = "Use custom model ID", ["th"] = "ใช้ Model ID กำหนดเอง" },
        ["settings.refreshModels"] = new() { ["en"] = "Refresh available Ollama models", ["th"] = "รีเฟรชรายการโมเดล Ollama" },
        ["settings.testConnection"] = new() { ["en"] = "Test Connection", ["th"] = "ทดสอบการเชื่อมต่อ" },
        ["settings.applyProvider"] = new() { ["en"] = "Apply Provider", ["th"] = "ใช้งาน Provider" },
        ["settings.gpuInfo"] = new() { ["en"] = "GPU Information", ["th"] = "ข้อมูล GPU" },
        ["settings.refreshGpu"] = new() { ["en"] = "Refresh GPU info", ["th"] = "รีเฟรชข้อมูล GPU" },
        ["settings.backend"] = new() { ["en"] = "Backend Settings", ["th"] = "ตั้งค่า Backend" },
        ["settings.gpuBackend"] = new() { ["en"] = "GPU Backend", ["th"] = "GPU Backend" },
        ["settings.gpuBackendDesc"] = new() { ["en"] = "Auto: tries CUDA first, falls back to CPU. Select CPU if you have no NVIDIA GPU.", ["th"] = "Auto: ลอง CUDA ก่อน ถ้าไม่ได้ใช้ CPU เลือก CPU หากไม่มี GPU NVIDIA" },
        ["settings.gpuLayers"] = new() { ["en"] = "GPU Layers:", ["th"] = "GPU Layers:" },
        ["settings.gpuLayersDesc"] = new() { ["en"] = "-1 = auto (all layers on GPU), 0 = CPU only. More layers = more VRAM used.", ["th"] = "-1 = อัตโนมัติ (ทุกชั้นบน GPU), 0 = CPU อย่างเดียว ยิ่งเยอะยิ่งใช้ VRAM มาก" },
        ["settings.batchSize"] = new() { ["en"] = "Batch Size", ["th"] = "Batch Size" },
        ["settings.batchSizeDesc"] = new() { ["en"] = "Prompt processing batch size. Higher = faster but uses more VRAM.", ["th"] = "ขนาด Batch สำหรับประมวลผล Prompt ยิ่งสูงยิ่งเร็วแต่ใช้ VRAM มากขึ้น" },
        ["settings.cpuThreads"] = new() { ["en"] = "CPU Threads:", ["th"] = "CPU Threads:" },
        ["settings.cpuThreadsDesc"] = new() { ["en"] = "Number of CPU threads for inference. 0 = auto-detect optimal count.", ["th"] = "จำนวน CPU Thread สำหรับ inference  0 = ตรวจหาจำนวนที่เหมาะสมอัตโนมัติ" },
        ["settings.modelStorageDir"] = new() { ["en"] = "Model Storage Directory", ["th"] = "โฟลเดอร์เก็บโมเดล" },
        ["settings.modelStorageDirDesc"] = new() { ["en"] = "Where downloaded GGUF models are stored", ["th"] = "โฟลเดอร์สำหรับเก็บโมเดล GGUF ที่ดาวน์โหลด" },
        ["settings.cacheDir"] = new() { ["en"] = "Cache Directory", ["th"] = "โฟลเดอร์ Cache" },
        ["settings.cacheDirDesc"] = new() { ["en"] = "Temporary cache for model operations", ["th"] = "แคชชั่วคราวสำหรับการทำงานกับโมเดล" },
        ["settings.logDir"] = new() { ["en"] = "Log Directory", ["th"] = "โฟลเดอร์ Log" },
        ["settings.logDirDesc"] = new() { ["en"] = "Where application logs are saved", ["th"] = "โฟลเดอร์สำหรับเก็บ Log ของแอป" },
        ["settings.tempDir"] = new() { ["en"] = "Temp Directory", ["th"] = "โฟลเดอร์ Temp" },
        ["settings.tempDirDesc"] = new() { ["en"] = "Temporary files for code execution", ["th"] = "ไฟล์ชั่วคราวสำหรับรันโค้ด" },
        ["settings.portableMode"] = new() { ["en"] = "Portable Mode", ["th"] = "โหมดพกพา" },
        ["settings.contextSizeDesc"] = new() { ["en"] = "Max tokens the model can process", ["th"] = "โทเค็นสูงสุดที่โมเดลประมวลผลได้" },
        ["settings.maxOutputTokens"] = new() { ["en"] = "Max Output Tokens", ["th"] = "จำนวนโทเค็นตอบสูงสุด" },
        ["settings.maxOutputTokensDesc"] = new() { ["en"] = "Maximum tokens per response", ["th"] = "โทเค็นสูงสุดต่อคำตอบ" },
        ["settings.topPDesc"] = new() { ["en"] = "Nucleus sampling threshold", ["th"] = "เกณฑ์ Nucleus sampling" },
        ["settings.temperatureDesc"] = new() { ["en"] = "Higher = more creative, lower = more precise", ["th"] = "สูง = สร้างสรรค์มากขึ้น, ต่ำ = แม่นยำมากขึ้น" },
        ["settings.repetitionPenaltyDesc"] = new() { ["en"] = "Penalize repetition in output", ["th"] = "ลดทอนการซ้ำในเอาต์พุต" },
        ["settings.anthropicAdvanced"] = new() { ["en"] = "Anthropic Advanced", ["th"] = "Anthropic ขั้นสูง" },
        ["settings.extendedThinking"] = new() { ["en"] = "Extended Thinking", ["th"] = "Extended Thinking" },
        ["settings.promptCaching"] = new() { ["en"] = "Prompt Caching", ["th"] = "Prompt Caching" },
        ["settings.huggingface"] = new() { ["en"] = "HuggingFace", ["th"] = "HuggingFace" },
        ["settings.memoryMgmt"] = new() { ["en"] = "Memory Management", ["th"] = "จัดการหน่วยความจำ" },
        ["settings.refresh"] = new() { ["en"] = "Refresh", ["th"] = "รีเฟรช" },
        ["settings.deleteSelected"] = new() { ["en"] = "Delete Selected", ["th"] = "ลบรายการที่เลือก" },
        ["settings.resetDefaults"] = new() { ["en"] = "Reset to Defaults", ["th"] = "คืนค่าเริ่มต้น" },
        ["settings.checkUpdates"] = new() { ["en"] = "Check for Updates", ["th"] = "ตรวจสอบการอัปเดต" },
        ["settings.microcompact"] = new() { ["en"] = "Microcompact", ["th"] = "Microcompact" },
        ["settings.microcompactDesc"] = new() { ["en"] = "Shrink old tool results before re-sending to the API. Saves context on long agentic runs.", ["th"] = "บีบอัดผล Tool เก่าก่อนส่งไป API อีกครั้ง ประหยัด Context บน Agent ที่ทำงานยาว" },
        ["settings.sessionMemory"] = new() { ["en"] = "Session Memory Extraction", ["th"] = "สกัดความจำจากเซสชัน" },
        ["settings.sessionMemoryDesc"] = new() { ["en"] = "After each session ends, scan the transcript and save durable facts as memory files (runs in background; opt-in).", ["th"] = "หลังจบแต่ละเซสชัน สแกนบทสนทนาและเก็บความจำที่สำคัญ (ทำงานเบื้องหลัง ต้องเปิดเอง)" },

        // ═══════ ACTIVATION ═══════
        ["activation.key"] = new() { ["en"] = "Activation Key", ["th"] = "คีย์ปลดล็อก" },
        ["activation.activate"] = new() { ["en"] = "Activate", ["th"] = "เปิดใช้งาน" },
        ["activation.deactivate"] = new() { ["en"] = "Deactivate", ["th"] = "ยกเลิกใช้งาน" },
        ["activation.transfer"] = new() { ["en"] = "⚠ Transfer to this device (old device will be revoked)", ["th"] = "⚠ ย้ายมาเครื่องนี้ (เครื่องเก่าจะถูกยกเลิก)" },
        ["activation.hint"] = new() { ["en"] = "Enter your activation key to unlock all advanced features.", ["th"] = "ใส่คีย์เพื่อปลดล็อกฟีเจอร์ขั้นสูงทั้งหมด" },

        // ═══════ FEATURES PAGE ═══════
        ["features.title"] = new() { ["en"] = "Features & Capabilities", ["th"] = "ฟีเจอร์และความสามารถ" },
        ["features.subtitle"] = new() { ["en"] = "Everything CluadeX can do for you", ["th"] = "ทุกสิ่งที่ CluadeX ทำได้" },
        ["features.core"] = new() { ["en"] = "Core Features", ["th"] = "ฟีเจอร์หลัก" },
        ["features.coreDesc"] = new() { ["en"] = "Built-in features available to everyone", ["th"] = "ฟีเจอร์พื้นฐานที่ทุกคนใช้ได้" },
        ["features.advanced"] = new() { ["en"] = "Advanced Features", ["th"] = "ฟีเจอร์ขั้นสูง" },
        ["features.advancedDesc"] = new() { ["en"] = "Requires API key from cloud providers", ["th"] = "ต้องใส่ API Key จากผู้ให้บริการ Cloud" },
        ["features.fun"] = new() { ["en"] = "Fun & Extras", ["th"] = "สนุกสนานและเพิ่มเติม" },
        ["features.funDesc"] = new() { ["en"] = "Optional fun features and customization", ["th"] = "ฟีเจอร์สนุกสนานและการปรับแต่งเพิ่มเติม" },
        ["features.tools"] = new() { ["en"] = "Agent Tools", ["th"] = "เครื่องมือ Agent" },
        ["features.toolsDesc"] = new() { ["en"] = "AI-powered tools for coding assistance", ["th"] = "เครื่องมือ AI สำหรับช่วยเขียนโค้ด" },
        ["features.security"] = new() { ["en"] = "Security & Privacy", ["th"] = "ความปลอดภัยและความเป็นส่วนตัว" },
        ["features.securityDesc"] = new() { ["en"] = "Protection and data safety features", ["th"] = "ฟีเจอร์ปกป้องข้อมูลและความปลอดภัย" },
        ["features.enabled"] = new() { ["en"] = "Enabled", ["th"] = "เปิดใช้งาน" },
        ["features.disabled"] = new() { ["en"] = "Disabled", ["th"] = "ปิดใช้งาน" },
        ["features.requiresKey"] = new() { ["en"] = "Requires API Key", ["th"] = "ต้องมี API Key" },
        ["features.free"] = new() { ["en"] = "Free", ["th"] = "ฟรี" },
        ["features.configureKey"] = new() { ["en"] = "Configure Key in Settings", ["th"] = "ตั้งค่า Key ในหน้าตั้งค่า" },

        // ═══════ FEATURE ITEMS ═══════
        // Core
        ["feature.localInference"] = new() { ["en"] = "Local GGUF Inference", ["th"] = "ประมวลผล GGUF บนเครื่อง" },
        ["feature.localInference.desc"] = new() { ["en"] = "Run AI models locally on your GPU/CPU with LLamaSharp. No internet required, fully private.", ["th"] = "รันโมเดล AI บนเครื่องของคุณด้วย GPU/CPU ผ่าน LLamaSharp ไม่ต้องใช้อินเทอร์เน็ต ข้อมูลเป็นส่วนตัว 100%" },
        ["feature.multiProvider"] = new() { ["en"] = "Multi-Provider AI", ["th"] = "รองรับหลายผู้ให้บริการ AI" },
        ["feature.multiProvider.desc"] = new() { ["en"] = "Switch between Local, OpenAI, Anthropic, Google Gemini, and Ollama providers.", ["th"] = "สลับระหว่าง Local, OpenAI, Anthropic, Google Gemini และ Ollama ได้ทันที" },
        ["feature.chatPersistence"] = new() { ["en"] = "Chat Persistence (SQLite)", ["th"] = "บันทึกแชทถาวร (SQLite)" },
        ["feature.chatPersistence.desc"] = new() { ["en"] = "All conversations saved locally with full-text search (FTS5). Never lose your chat history.", ["th"] = "บันทึกการสนทนาทั้งหมดในเครื่องพร้อมค้นหาข้อความเต็ม (FTS5) ไม่สูญหาย" },
        ["feature.markdown"] = new() { ["en"] = "Markdown & Syntax Highlighting", ["th"] = "Markdown และไฮไลท์โค้ด" },
        ["feature.markdown.desc"] = new() { ["en"] = "Rich text rendering with code blocks, tables, and syntax-highlighted code snippets.", ["th"] = "แสดงผลข้อความสวยงามพร้อมบล็อกโค้ด ตาราง และไฮไลท์โค้ดสีสัน" },
        ["feature.gpuDetection"] = new() { ["en"] = "GPU Auto-Detection", ["th"] = "ตรวจจับ GPU อัตโนมัติ" },
        ["feature.gpuDetection.desc"] = new() { ["en"] = "Automatically detects your NVIDIA GPU and VRAM for optimal model loading.", ["th"] = "ตรวจจับ GPU NVIDIA และ VRAM อัตโนมัติเพื่อโหลดโมเดลได้เหมาะสม" },
        ["feature.darkTheme"] = new() { ["en"] = "Catppuccin Mocha Theme", ["th"] = "ธีม Catppuccin Mocha" },
        ["feature.darkTheme.desc"] = new() { ["en"] = "Beautiful dark theme with metallic gradients, drop shadows, and rounded corners.", ["th"] = "ธีมมืดสวยงามพร้อมกราเดียนท์เมทัลลิก เงาตกกระทบ และขอบมน" },
        ["feature.huggingface"] = new() { ["en"] = "HuggingFace Model Hub", ["th"] = "ดาวน์โหลดจาก HuggingFace" },
        ["feature.huggingface.desc"] = new() { ["en"] = "Browse, search, and download GGUF models directly from HuggingFace Hub.", ["th"] = "ค้นหาและดาวน์โหลดโมเดล GGUF จาก HuggingFace Hub ได้โดยตรง" },
        ["feature.i18n"] = new() { ["en"] = "Thai/English Localization", ["th"] = "รองรับภาษาไทย/อังกฤษ" },
        ["feature.i18n.desc"] = new() { ["en"] = "Full Thai and English language support. Switch anytime from Settings.", ["th"] = "รองรับภาษาไทยและอังกฤษเต็มรูปแบบ สลับได้ทุกเมื่อจากหน้าตั้งค่า" },

        // Advanced (requires API key)
        ["feature.openai"] = new() { ["en"] = "OpenAI (GPT-4, o1, o3)", ["th"] = "OpenAI (GPT-4, o1, o3)" },
        ["feature.openai.desc"] = new() { ["en"] = "Use OpenAI's GPT-4o, o1, o3 models for coding. Requires OpenAI API key.", ["th"] = "ใช้โมเดล GPT-4o, o1, o3 ของ OpenAI สำหรับเขียนโค้ด ต้องมี API Key ของ OpenAI" },
        ["feature.anthropic"] = new() { ["en"] = "Anthropic (Claude 4)", ["th"] = "Anthropic (Claude 4)" },
        ["feature.anthropic.desc"] = new() { ["en"] = "Use Anthropic's Claude Sonnet/Opus for advanced coding assistance. Requires Anthropic API key.", ["th"] = "ใช้ Claude Sonnet/Opus ของ Anthropic สำหรับช่วยเขียนโค้ดขั้นสูง ต้องมี API Key ของ Anthropic" },
        ["feature.gemini"] = new() { ["en"] = "Google Gemini", ["th"] = "Google Gemini" },
        ["feature.gemini.desc"] = new() { ["en"] = "Use Google's Gemini Pro/Ultra models. Requires Google AI API key.", ["th"] = "ใช้โมเดล Gemini Pro/Ultra ของ Google ต้องมี Google AI API Key" },
        ["feature.ollama"] = new() { ["en"] = "Ollama Integration", ["th"] = "เชื่อมต่อ Ollama" },
        ["feature.ollama.desc"] = new() { ["en"] = "Connect to local Ollama server for running models. Free — requires Ollama installed.", ["th"] = "เชื่อมต่อ Ollama เพื่อรันโมเดลบนเครื่อง ฟรี — ต้องติดตั้ง Ollama ก่อน" },

        // Agent Tools
        ["feature.codeExecution"] = new() { ["en"] = "Code Execution", ["th"] = "รันโค้ด" },
        ["feature.codeExecution.desc"] = new() { ["en"] = "Execute code snippets in multiple languages with sandboxed environment.", ["th"] = "รันโค้ดหลายภาษาในสภาพแวดล้อมที่ปลอดภัย (Sandbox)" },
        ["feature.fileSystem"] = new() { ["en"] = "File System Tools", ["th"] = "จัดการไฟล์" },
        ["feature.fileSystem.desc"] = new() { ["en"] = "Read, write, search, and manage project files with permission controls.", ["th"] = "อ่าน เขียน ค้นหา และจัดการไฟล์โปรเจกต์พร้อมระบบควบคุมสิทธิ์" },
        ["feature.git"] = new() { ["en"] = "Git Integration", ["th"] = "จัดการ Git" },
        ["feature.git.desc"] = new() { ["en"] = "Full Git operations: commit, branch, merge, diff, stash, tag — all from chat.", ["th"] = "ใช้ Git ครบ: commit, branch, merge, diff, stash, tag — ทั้งหมดจากแชท" },
        ["feature.github"] = new() { ["en"] = "GitHub Integration", ["th"] = "เชื่อมต่อ GitHub" },
        ["feature.github.desc"] = new() { ["en"] = "Create PRs, issues, search repos, clone projects via GitHub CLI.", ["th"] = "สร้าง PR, Issues, ค้นหา repo, clone โปรเจกต์ผ่าน GitHub CLI" },
        ["feature.webFetch"] = new() { ["en"] = "Web Fetch", ["th"] = "ดึงข้อมูลเว็บ" },
        ["feature.webFetch.desc"] = new() { ["en"] = "Fetch web pages and APIs, convert HTML to text for analysis.", ["th"] = "ดึงหน้าเว็บและ API แปลง HTML เป็นข้อความเพื่อวิเคราะห์" },
        ["feature.contextMemory"] = new() { ["en"] = "Context Memory", ["th"] = "หน่วยความจำบริบท" },
        ["feature.contextMemory.desc"] = new() { ["en"] = "Smart context management to keep relevant code and files in memory.", ["th"] = "จัดการบริบทอัจฉริยะ เก็บโค้ดและไฟล์ที่เกี่ยวข้องไว้ในหน่วยความจำ" },
        ["feature.smartEditing"] = new() { ["en"] = "Smart Code Editing", ["th"] = "แก้โค้ดอัจฉริยะ" },
        ["feature.smartEditing.desc"] = new() { ["en"] = "AI-powered code editing with auto-fix, refactoring, and intelligent suggestions.", ["th"] = "แก้โค้ดด้วย AI พร้อม auto-fix, refactoring และคำแนะนำอัจฉริยะ" },

        // Security
        ["feature.dpapi"] = new() { ["en"] = "DPAPI Key Encryption", ["th"] = "เข้ารหัส Key ด้วย DPAPI" },
        ["feature.dpapi.desc"] = new() { ["en"] = "All API keys encrypted at rest using Windows Data Protection API. Only your Windows account can decrypt.", ["th"] = "API Key ทั้งหมดเข้ารหัสด้วย Windows DPAPI มีเฉพาะบัญชี Windows ของคุณเท่านั้นที่ถอดรหัสได้" },
        ["feature.permissions"] = new() { ["en"] = "Permission System", ["th"] = "ระบบสิทธิ์" },
        ["feature.permissions.desc"] = new() { ["en"] = "Allow/Deny/Ask rules for file, command, and network access. First-match-wins.", ["th"] = "กฎ อนุญาต/ปฏิเสธ/ถาม สำหรับการเข้าถึงไฟล์ คำสั่ง และเครือข่าย" },
        ["feature.commandBlock"] = new() { ["en"] = "Dangerous Command Blocking", ["th"] = "บล็อกคำสั่งอันตราย" },
        ["feature.commandBlock.desc"] = new() { ["en"] = "Blocks 30+ dangerous shell commands (rm -rf, format, del, etc.) automatically.", ["th"] = "บล็อกคำสั่งอันตราย 30+ รายการ (rm -rf, format, del ฯลฯ) อัตโนมัติ" },
        ["feature.pathSafety"] = new() { ["en"] = "Path Traversal Protection", ["th"] = "ป้องกัน Path Traversal" },
        ["feature.pathSafety.desc"] = new() { ["en"] = "Prevents access outside project directory. Rejects absolute paths and ../ traversal.", ["th"] = "ป้องกันการเข้าถึงนอกไดเรกทอรีโปรเจกต์ ปฏิเสธ absolute path และ ../" },
        ["feature.noTelemetry"] = new() { ["en"] = "Zero Telemetry", ["th"] = "ไม่มี Telemetry" },
        ["feature.noTelemetry.desc"] = new() { ["en"] = "CluadeX sends ZERO analytics or tracking data. Your code stays on your machine.", ["th"] = "CluadeX ไม่ส่งข้อมูลใดๆ กลับไปที่ใด โค้ดของคุณอยู่ในเครื่องคุณเท่านั้น" },

        // Fun
        ["feature.buddy"] = new() { ["en"] = "Buddy Companion", ["th"] = "สัตว์เลี้ยง Buddy" },
        ["feature.buddy.desc"] = new() { ["en"] = "A cute AI companion pet generated from your user ID. 18 species, 5 rarity levels, hats, shiny variants! Pet it for hearts!", ["th"] = "สัตว์เลี้ยง AI น่ารักที่สร้างจาก User ID ของคุณ มี 18 สายพันธุ์, 5 ระดับความหายาก, หมวก, แบบเรืองแสง! ลูบเพื่อให้หัวใจ!" },
        ["feature.plugins"] = new() { ["en"] = "Plugin System", ["th"] = "ระบบปลั๊กอิน" },
        ["feature.plugins.desc"] = new() { ["en"] = "Extend CluadeX with custom plugins. Browse, install, enable/disable from Plugin Manager.", ["th"] = "ขยายความสามารถด้วยปลั๊กอิน เรียกดู ติดตั้ง เปิด/ปิด จาก Plugin Manager" },
        ["feature.taskManager"] = new() { ["en"] = "Task Manager", ["th"] = "จัดการงาน" },
        ["feature.taskManager.desc"] = new() { ["en"] = "Run background shell commands with status tracking, output capture, and stop/kill.", ["th"] = "รันคำสั่ง Shell เบื้องหลังพร้อมติดตามสถานะ บันทึกผลลัพธ์ และหยุด/ฆ่ากระบวนการ" },

        // ═══════ PLUGIN MANAGER ═══════
        ["plugins.title"] = new() { ["en"] = "Plugin Manager", ["th"] = "จัดการปลั๊กอิน" },
        ["plugins.subtitle"] = new() { ["en"] = "Browse catalog, install, and manage plugins", ["th"] = "เรียกดูแค็ตตาล็อก ติดตั้ง และจัดการปลั๊กอิน" },
        ["plugins.installed"] = new() { ["en"] = "Installed", ["th"] = "ติดตั้งแล้ว" },
        ["plugins.catalog"] = new() { ["en"] = "Catalog", ["th"] = "แค็ตตาล็อก" },
        ["plugins.install"] = new() { ["en"] = "Install", ["th"] = "ติดตั้ง" },
        ["plugins.uninstall"] = new() { ["en"] = "Uninstall", ["th"] = "ถอนการติดตั้ง" },
        ["plugins.enable"] = new() { ["en"] = "Enable", ["th"] = "เปิดใช้" },
        ["plugins.disable"] = new() { ["en"] = "Disable", ["th"] = "ปิดใช้" },
        ["plugins.search"] = new() { ["en"] = "Search plugins...", ["th"] = "ค้นหาปลั๊กอิน..." },
        ["plugins.noPlugins"] = new() { ["en"] = "No plugins installed yet.\nBrowse the Catalog tab to get started!", ["th"] = "ยังไม่มีปลั๊กอินที่ติดตั้ง\nไปที่แท็บแค็ตตาล็อกเพื่อเริ่มต้น!" },
        ["plugins.selectPlugin"] = new() { ["en"] = "Select a plugin to view details", ["th"] = "เลือกปลั๊กอินเพื่อดูรายละเอียด" },
        ["plugins.hookEvents"] = new() { ["en"] = "Hook Events", ["th"] = "เหตุการณ์ Hook" },
        ["plugins.whatItDoes"] = new() { ["en"] = "What it does", ["th"] = "ทำอะไรได้บ้าง" },
        ["plugins.author"] = new() { ["en"] = "Author", ["th"] = "ผู้สร้าง" },
        ["plugins.category"] = new() { ["en"] = "Category", ["th"] = "หมวดหมู่" },
        ["plugins.version"] = new() { ["en"] = "Version", ["th"] = "เวอร์ชัน" },
        ["plugins.status"] = new() { ["en"] = "Status", ["th"] = "สถานะ" },
        ["plugins.installedBadge"] = new() { ["en"] = "INSTALLED", ["th"] = "ติดตั้งแล้ว" },
        ["plugins.availableBadge"] = new() { ["en"] = "AVAILABLE", ["th"] = "พร้อมติดตั้ง" },

        // ═══════ CHAT VIEW ═══════
        ["chat.placeholder"] = new() { ["en"] = "Type a message...", ["th"] = "พิมพ์ข้อความ..." },
        ["chat.send"] = new() { ["en"] = "Send", ["th"] = "ส่ง" },
        ["chat.stop"] = new() { ["en"] = "Stop", ["th"] = "หยุด" },
        ["chat.thinking"] = new() { ["en"] = "Thinking...", ["th"] = "กำลังคิด..." },
        ["chat.you"] = new() { ["en"] = "You", ["th"] = "คุณ" },

        // ═══════ MODEL MANAGER ═══════
        ["models.title"] = new() { ["en"] = "Model Manager", ["th"] = "จัดการโมเดล" },
        ["models.subtitle"] = new() { ["en"] = "Download and manage GGUF models", ["th"] = "ดาวน์โหลดและจัดการโมเดล GGUF" },
        ["models.localModels"] = new() { ["en"] = "Local Models", ["th"] = "โมเดลในเครื่อง" },
        ["models.download"] = new() { ["en"] = "Download from HuggingFace", ["th"] = "ดาวน์โหลดจาก HuggingFace" },

        // ═══════ BUDDY ═══════
        ["buddy.pet"] = new() { ["en"] = "Pet me!", ["th"] = "ลูบฉันสิ!" },
        ["buddy.stats"] = new() { ["en"] = "Stats", ["th"] = "สถิติ" },
        ["buddy.rarity"] = new() { ["en"] = "Rarity", ["th"] = "ความหายาก" },
        ["buddy.species"] = new() { ["en"] = "Species", ["th"] = "สายพันธุ์" },
        ["buddy.hatched"] = new() { ["en"] = "Hatched", ["th"] = "ฟักเมื่อ" },
        ["buddy.shiny"] = new() { ["en"] = "SHINY!", ["th"] = "เรืองแสง!" },
        ["buddy.debugging"] = new() { ["en"] = "Debugging", ["th"] = "ดีบัก" },
        ["buddy.patience"] = new() { ["en"] = "Patience", ["th"] = "อดทน" },
        ["buddy.chaos"] = new() { ["en"] = "Chaos", ["th"] = "วุ่นวาย" },
        ["buddy.wisdom"] = new() { ["en"] = "Wisdom", ["th"] = "ปัญญา" },
        ["buddy.snark"] = new() { ["en"] = "Snark", ["th"] = "เสียดสี" },

        // ═══════ COMMON ═══════
        ["common.save"] = new() { ["en"] = "Save", ["th"] = "บันทึก" },
        ["common.cancel"] = new() { ["en"] = "Cancel", ["th"] = "ยกเลิก" },
        ["common.delete"] = new() { ["en"] = "Delete", ["th"] = "ลบ" },
        ["common.confirm"] = new() { ["en"] = "Confirm", ["th"] = "ยืนยัน" },
        ["common.close"] = new() { ["en"] = "Close", ["th"] = "ปิด" },
        ["common.search"] = new() { ["en"] = "Search", ["th"] = "ค้นหา" },
        ["common.loading"] = new() { ["en"] = "Loading...", ["th"] = "กำลังโหลด..." },
        ["common.error"] = new() { ["en"] = "Error", ["th"] = "ข้อผิดพลาด" },
        ["common.success"] = new() { ["en"] = "Success", ["th"] = "สำเร็จ" },
        ["common.on"] = new() { ["en"] = "ON", ["th"] = "เปิด" },
        ["common.off"] = new() { ["en"] = "OFF", ["th"] = "ปิด" },

        // ═══════ LOADING OVERLAY ═══════
        ["loading.title"] = new() { ["en"] = "Loading Model", ["th"] = "กำลังโหลดโมเดล" },
        ["loading.hint"] = new() { ["en"] = "Please wait while the model loads into memory...", ["th"] = "กรุณารอสักครู่ขณะโหลดโมเดลเข้าหน่วยความจำ..." },

        // ═══════ RARITY NAMES ═══════
        ["rarity.common"] = new() { ["en"] = "Common", ["th"] = "ธรรมดา" },
        ["rarity.uncommon"] = new() { ["en"] = "Uncommon", ["th"] = "ไม่ธรรมดา" },
        ["rarity.rare"] = new() { ["en"] = "Rare", ["th"] = "หายาก" },
        ["rarity.epic"] = new() { ["en"] = "Epic", ["th"] = "มหากาพย์" },
        ["rarity.legendary"] = new() { ["en"] = "Legendary", ["th"] = "ตำนาน" },

        // ═══════ SPECIES NAMES ═══════
        ["species.duck"] = new() { ["en"] = "Duck", ["th"] = "เป็ด" },
        ["species.goose"] = new() { ["en"] = "Goose", ["th"] = "ห่าน" },
        ["species.blob"] = new() { ["en"] = "Blob", ["th"] = "บล็อบ" },
        ["species.cat"] = new() { ["en"] = "Cat", ["th"] = "แมว" },
        ["species.dragon"] = new() { ["en"] = "Dragon", ["th"] = "มังกร" },
        ["species.octopus"] = new() { ["en"] = "Octopus", ["th"] = "ปลาหมึก" },
        ["species.owl"] = new() { ["en"] = "Owl", ["th"] = "นกฮูก" },
        ["species.penguin"] = new() { ["en"] = "Penguin", ["th"] = "เพนกวิน" },
        ["species.turtle"] = new() { ["en"] = "Turtle", ["th"] = "เต่า" },
        ["species.snail"] = new() { ["en"] = "Snail", ["th"] = "หอยทาก" },
        ["species.ghost"] = new() { ["en"] = "Ghost", ["th"] = "ผี" },
        ["species.axolotl"] = new() { ["en"] = "Axolotl", ["th"] = "แอกโซลอเติล" },
        ["species.capybara"] = new() { ["en"] = "Capybara", ["th"] = "คาปิบารา" },
        ["species.cactus"] = new() { ["en"] = "Cactus", ["th"] = "กระบองเพชร" },
        ["species.robot"] = new() { ["en"] = "Robot", ["th"] = "หุ่นยนต์" },
        ["species.rabbit"] = new() { ["en"] = "Rabbit", ["th"] = "กระต่าย" },
        ["species.mushroom"] = new() { ["en"] = "Mushroom", ["th"] = "เห็ด" },
        ["species.chonk"] = new() { ["en"] = "Chonk", ["th"] = "อ้วนกลม" },

        // ── auto-wired page strings ──
        ["hooks.title"] = new() { ["en"] = "Hook Library", ["th"] = "คลังฮุก" },
        ["hooks.filter"] = new() { ["en"] = "filter…", ["th"] = "กรอง…" },
        ["hooks.toggle"] = new() { ["en"] = "Toggle", ["th"] = "เปิด/ปิด" },
        ["hooks.scriptPreview"] = new() { ["en"] = "SCRIPT PREVIEW", ["th"] = "ตัวอย่างสคริปต์" },
        ["tasks.title"] = new() { ["en"] = "Task Manager", ["th"] = "จัดการงาน" },
        ["tasks.subtitle"] = new() { ["en"] = "Run and monitor system commands", ["th"] = "รันและติดตามคำสั่งระบบ" },
        ["tasks.clearCompleted"] = new() { ["en"] = "Clear Completed", ["th"] = "ล้างงานที่เสร็จแล้ว" },
        ["tasks.colName"] = new() { ["en"] = "Name", ["th"] = "ชื่อ" },
        ["tasks.colStatus"] = new() { ["en"] = "Status", ["th"] = "สถานะ" },
        ["tasks.colCommand"] = new() { ["en"] = "Command", ["th"] = "คำสั่ง" },
        ["tasks.stop"] = new() { ["en"] = "Stop", ["th"] = "หยุด" },
        ["tasks.start"] = new() { ["en"] = "Start Task", ["th"] = "เริ่มงาน" },
        ["tasks.output"] = new() { ["en"] = "Output", ["th"] = "ผลลัพธ์" },
        ["subagents.title"] = new() { ["en"] = "Subagents", ["th"] = "Subagent" },
        ["subagents.whenToUse"] = new() { ["en"] = "WHEN TO USE", ["th"] = "ใช้เมื่อไหร่" },
        ["subagents.allowedTools"] = new() { ["en"] = "ALLOWED TOOLS", ["th"] = "เครื่องมือที่อนุญาต" },
        ["subagents.invokeSnippet"] = new() { ["en"] = "INVOKE SNIPPET", ["th"] = "โค้ดสำหรับเรียกใช้" },
        ["subagents.systemPersona"] = new() { ["en"] = "SYSTEM PERSONA", ["th"] = "บุคลิกของเอเจนต์" },
        ["skills.title"] = new() { ["en"] = "Skills", ["th"] = "Skill" },
        ["skills.openFolder"] = new() { ["en"] = "Open skills folder", ["th"] = "เปิดโฟลเดอร์ skill" },
        ["skills.refresh"] = new() { ["en"] = "Refresh", ["th"] = "รีเฟรช" },
        ["skills.allowedTools"] = new() { ["en"] = "ALLOWED TOOLS", ["th"] = "เครื่องมือที่อนุญาต" },
        ["skills.invokeFromChat"] = new() { ["en"] = "INVOKE FROM CHAT", ["th"] = "เรียกใช้จากแชท" },
        ["skills.promptBody"] = new() { ["en"] = "PROMPT BODY", ["th"] = "เนื้อหา prompt" },

        // ── auto-wired page strings ──
        ["plugins.installedCaps"] = new() { ["en"] = "INSTALLED", ["th"] = "ที่ติดตั้งแล้ว" },
        ["plugins.folder"] = new() { ["en"] = "Plugins folder", ["th"] = "โฟลเดอร์ปลั๊กอิน" },
        ["plugins.installCustom"] = new() { ["en"] = "Install custom", ["th"] = "ติดตั้งจากไฟล์เอง" },
        ["plugins.refresh"] = new() { ["en"] = "Refresh", ["th"] = "รีเฟรช" },
        ["plugins.tabInstalled"] = new() { ["en"] = "Installed", ["th"] = "ติดตั้งแล้ว" },
        ["plugins.tabCatalog"] = new() { ["en"] = "Catalog", ["th"] = "แคตตาล็อก" },
        ["plugins.pickHint"] = new() { ["en"] = "Pick a plugin on the left to see details", ["th"] = "เลือกปลั๊กอินทางซ้ายเพื่อดูรายละเอียด" },
        ["plugins.hooks"] = new() { ["en"] = "HOOKS", ["th"] = "ฮุก" },
        ["debuglog.title"] = new() { ["en"] = "Debug Log", ["th"] = "บันทึกดีบัก" },
        ["debuglog.testTip"] = new() { ["en"] = "Emit 5 test entries (Trace..Error)", ["th"] = "สร้างรายการทดสอบ 5 บรรทัด (Trace..Error)" },
        ["debuglog.test"] = new() { ["en"] = "Test", ["th"] = "ทดสอบ" },
        ["debuglog.copyAll"] = new() { ["en"] = "Copy all", ["th"] = "คัดลอกทั้งหมด" },
        ["debuglog.saveDump"] = new() { ["en"] = "Save dump", ["th"] = "บันทึกไฟล์" },
        ["debuglog.logFolder"] = new() { ["en"] = "Log folder", ["th"] = "โฟลเดอร์บันทึก" },
        ["debuglog.clear"] = new() { ["en"] = "Clear", ["th"] = "ล้าง" },
        ["debuglog.minLevel"] = new() { ["en"] = "MIN LEVEL", ["th"] = "ระดับต่ำสุด" },
        ["debuglog.category"] = new() { ["en"] = "CATEGORY", ["th"] = "หมวด" },
        ["debuglog.filterTip"] = new() { ["en"] = "Filter by substring in message or exception", ["th"] = "กรองด้วยข้อความบางส่วนในข้อความหรือ exception" },
        ["debuglog.autoScroll"] = new() { ["en"] = "Auto-scroll", ["th"] = "เลื่อนอัตโนมัติ" },
        ["perms.title"] = new() { ["en"] = "Permissions", ["th"] = "สิทธิ์การเข้าถึง" },
        ["perms.subtitle"] = new() { ["en"] = "Control what CluadeX is allowed to access. Rules are evaluated top-down, first match wins.", ["th"] = "กำหนดสิ่งที่ CluadeX เข้าถึงได้ กฎถูกตรวจจากบนลงล่าง ข้อแรกที่ตรงจะถูกใช้" },
        ["perms.activeRules"] = new() { ["en"] = "Active Rules", ["th"] = "กฎที่ใช้อยู่" },
        ["perms.noRules"] = new() { ["en"] = "No rules defined. All actions will prompt for confirmation.", ["th"] = "ยังไม่มีกฎ ทุกการกระทำจะถามยืนยันก่อน" },
        ["perms.removeSelected"] = new() { ["en"] = "Remove Selected Rule", ["th"] = "ลบกฎที่เลือก" },
        ["perms.addRule"] = new() { ["en"] = "Add Rule", ["th"] = "เพิ่มกฎ" },
        ["perms.pattern"] = new() { ["en"] = "Pattern", ["th"] = "รูปแบบ" },
        ["perms.patternDesc"] = new() { ["en"] = "Glob pattern to match resources. Use * as wildcard (e.g. *.exe, /home/user/*, https://*.example.com/*)", ["th"] = "รูปแบบ glob สำหรับจับคู่ทรัพยากร ใช้ * เป็นตัวแทน (เช่น *.exe, /home/user/*, https://*.example.com/*)" },
        ["perms.scope"] = new() { ["en"] = "Scope", ["th"] = "ขอบเขต" },
        ["perms.scopeDesc"] = new() { ["en"] = "What type of access this rule applies to", ["th"] = "กฎนี้ใช้กับการเข้าถึงประเภทใด" },
        ["perms.addAllow"] = new() { ["en"] = "Add as Allow", ["th"] = "เพิ่มเป็นอนุญาต" },
        ["perms.addDeny"] = new() { ["en"] = "Add as Deny", ["th"] = "เพิ่มเป็นปฏิเสธ" },
        ["perms.save"] = new() { ["en"] = "Save", ["th"] = "บันทึก" },
        ["perms.refresh"] = new() { ["en"] = "Refresh", ["th"] = "รีเฟรช" },
        ["timemachine.title"] = new() { ["en"] = "Time Machine", ["th"] = "ย้อนเวลา" },
        ["timemachine.subtitle"] = new() { ["en"] = "Rewind your project to any commit · safe rollback with auto-stash", ["th"] = "ย้อนโปรเจคไปคอมมิตใดก็ได้ · ปลอดภัยด้วย auto-stash" },
        ["timemachine.filterAll"] = new() { ["en"] = "All", ["th"] = "ทั้งหมด" },
        ["timemachine.filterAgent"] = new() { ["en"] = "Agent only", ["th"] = "เฉพาะของ AI" },
        ["timemachine.timeline"] = new() { ["en"] = "Timeline", ["th"] = "ไทม์ไลน์" },
        ["timemachine.rewindHere"] = new() { ["en"] = "Rewind to here", ["th"] = "ย้อนมาจุดนี้" },
        ["timemachine.branchHere"] = new() { ["en"] = "Branch from here", ["th"] = "แตก branch จากจุดนี้" },
        ["timemachine.cherryPick"] = new() { ["en"] = "Cherry-pick", ["th"] = "Cherry-pick" },
        ["timemachine.changes"] = new() { ["en"] = "Changes", ["th"] = "ไฟล์ที่เปลี่ยน" },
        ["timemachine.rewindConfirmTitle"] = new() { ["en"] = "Rewind to commit?", ["th"] = "ย้อนไปคอมมิตนี้?" },
        ["timemachine.snapshotBranch"] = new() { ["en"] = "Create a snapshot branch before rewinding", ["th"] = "สร้าง branch สำรองก่อนย้อน" },
        ["timemachine.cancel"] = new() { ["en"] = "Cancel", ["th"] = "ยกเลิก" },
        ["timemachine.confirmRewind"] = new() { ["en"] = "Confirm rewind", ["th"] = "ยืนยันการย้อน" },
        ["timemachine.rewinding"] = new() { ["en"] = "Rewinding project…", ["th"] = "กำลังย้อนโปรเจค…" },
        ["timemachine.rewindSteps"] = new() { ["en"] = "auto-stash · reset --hard · restore working tree", ["th"] = "auto-stash · reset --hard · คืนไฟล์ในเวิร์กทรี" },

        // ── auto-wired page strings ──
        ["mcp.command"] = new() { ["en"] = "Command", ["th"] = "คำสั่ง" },
        ["mcp.serverLog"] = new() { ["en"] = "Server Log", ["th"] = "บันทึกของเซิร์ฟเวอร์" },
        ["mcp.argsHint"] = new() { ["en"] = "Arguments (space-separated)", ["th"] = "อาร์กิวเมนต์ (คั่นด้วยช่องว่าง)" },
        ["mcp.envHint"] = new() { ["en"] = "Environment Variables (KEY=VALUE per line)", ["th"] = "ตัวแปรสภาพแวดล้อม (KEY=VALUE บรรทัดละตัว)" },
        ["mcp.save"] = new() { ["en"] = "Save", ["th"] = "บันทึก" },
        ["mcp.cancel"] = new() { ["en"] = "Cancel", ["th"] = "ยกเลิก" },
        ["mcp.addServerTitle"] = new() { ["en"] = "Add MCP Server", ["th"] = "เพิ่มเซิร์ฟเวอร์ MCP" },
        ["mcp.name"] = new() { ["en"] = "Name", ["th"] = "ชื่อ" },
        ["mcp.arguments"] = new() { ["en"] = "Arguments", ["th"] = "อาร์กิวเมนต์" },
        ["mcp.add"] = new() { ["en"] = "Add", ["th"] = "เพิ่ม" },
        ["mcp.start"] = new() { ["en"] = "Start", ["th"] = "เริ่ม" },
        ["mcp.stop"] = new() { ["en"] = "Stop", ["th"] = "หยุด" },
        ["mcp.restart"] = new() { ["en"] = "Restart", ["th"] = "เริ่มใหม่" },
        ["mcp.edit"] = new() { ["en"] = "Edit", ["th"] = "แก้ไข" },
        ["mcp.toggle"] = new() { ["en"] = "Toggle", ["th"] = "เปิด/ปิด" },
        ["mcp.remove"] = new() { ["en"] = "Remove", ["th"] = "ลบ" },
        ["mcp.addServer"] = new() { ["en"] = "Add Server", ["th"] = "เพิ่มเซิร์ฟเวอร์" },
        ["mcp.startAll"] = new() { ["en"] = "Start All", ["th"] = "เริ่มทั้งหมด" },
        ["mcp.refresh"] = new() { ["en"] = "Refresh", ["th"] = "รีเฟรช" },
        ["shield.title"] = new() { ["en"] = "SecurityShield", ["th"] = "SecurityShield" },
        ["shield.scanProject"] = new() { ["en"] = "Scan project", ["th"] = "สแกนโปรเจค" },
        ["shield.cancelScan"] = new() { ["en"] = "Cancel scan", ["th"] = "ยกเลิกการสแกน" },
        ["shield.clear"] = new() { ["en"] = "Clear", ["th"] = "ล้าง" },
        ["shield.filterTip"] = new() { ["en"] = "Filter findings by substring", ["th"] = "กรองผลด้วยข้อความบางส่วน" },
        ["shield.location"] = new() { ["en"] = "LOCATION", ["th"] = "ตำแหน่ง" },
        ["shield.offendingLine"] = new() { ["en"] = "OFFENDING LINE", ["th"] = "บรรทัดที่มีปัญหา" },
        ["shield.suggestedFix"] = new() { ["en"] = "SUGGESTED FIX", ["th"] = "วิธีแก้ที่แนะนำ" },
        ["shield.openInEditor"] = new() { ["en"] = "Open file in editor", ["th"] = "เปิดไฟล์ในอีดิเตอร์" },
        ["editor.closeTab"] = new() { ["en"] = "Close tab", ["th"] = "ปิดแท็บ" },
        ["editor.explorer"] = new() { ["en"] = "EXPLORER", ["th"] = "สำรวจไฟล์" },
        ["editor.connectRepo"] = new() { ["en"] = "Connect GitHub repo (clone + open)", ["th"] = "เชื่อม repo GitHub (โคลนแล้วเปิด)" },
        ["editor.openChangeFolder"] = new() { ["en"] = "Open / change project folder", ["th"] = "เปิด / เปลี่ยนโฟลเดอร์โปรเจค" },
        ["editor.refreshTree"] = new() { ["en"] = "Refresh tree", ["th"] = "รีเฟรชรายการไฟล์" },
        ["editor.noProject"] = new() { ["en"] = "No project open", ["th"] = "ยังไม่ได้เปิดโปรเจค" },
        ["editor.noProjectHint"] = new() { ["en"] = "Click the folder icon in the title bar to open a project.", ["th"] = "คลิกไอคอนโฟลเดอร์บนแถบหัวเรื่องเพื่อเปิดโปรเจค" },
        ["editor.openFolder"] = new() { ["en"] = "Open Folder", ["th"] = "เปิดโฟลเดอร์" },
        ["editor.sourceControl"] = new() { ["en"] = "SOURCE CONTROL", ["th"] = "ควบคุมเวอร์ชัน" },
        ["editor.switchBranch"] = new() { ["en"] = "Switch branch (git checkout)", ["th"] = "สลับ branch (git checkout)" },
        ["editor.refreshGit"] = new() { ["en"] = "Refresh git status", ["th"] = "รีเฟรชสถานะ git" },
        ["editor.viewDiff"] = new() { ["en"] = "View diff", ["th"] = "ดู diff" },
        ["editor.commitMessage"] = new() { ["en"] = "Commit message", ["th"] = "ข้อความคอมมิต" },
        ["editor.stageAndCommit"] = new() { ["en"] = "Stage all changes and commit", ["th"] = "stage ทุกไฟล์แล้วคอมมิต" },
        ["editor.commit"] = new() { ["en"] = "Commit", ["th"] = "คอมมิต" },
        ["editor.save"] = new() { ["en"] = "Save", ["th"] = "บันทึก" },
        ["editor.saveAll"] = new() { ["en"] = "Save All", ["th"] = "บันทึกทั้งหมด" },
        ["editor.previewTip"] = new() { ["en"] = "Open this file in its default app (browser for HTML) to review the result", ["th"] = "เปิดไฟล์นี้ด้วยโปรแกรมเริ่มต้น (HTML เปิดในเบราว์เซอร์) เพื่อดูผลลัพธ์" },
        ["editor.preview"] = new() { ["en"] = "Preview", ["th"] = "ดูตัวอย่าง" },
        ["editor.openFileHint"] = new() { ["en"] = "Open a file from the tree to start editing", ["th"] = "เลือกไฟล์จากรายการทางซ้ายเพื่อเริ่มแก้ไข" },
        ["editor.askAiHint"] = new() { ["en"] = "Or ask the AI on the right to write code for you →", ["th"] = "หรือสั่ง AI ทางขวาให้เขียนโค้ดให้ →" },
        ["editor.terminal"] = new() { ["en"] = "Terminal", ["th"] = "เทอร์มินัล" },

        // ── auto-wired page strings ──
        ["instincts.title"] = new() { ["en"] = "Instincts", ["th"] = "สัญชาตญาณที่เรียนรู้" },
        ["instincts.syncAllTip"] = new() { ["en"] = "Push every STRONG instinct as a coding-lesson note in your ObsidianX vault", ["th"] = "ส่งสัญชาตญาณระดับ STRONG ทุกข้อไปเป็นโน้ตบทเรียนใน ObsidianX" },
        ["instincts.syncAllStrong"] = new() { ["en"] = "Sync all STRONG", ["th"] = "ซิงก์ทุกข้อระดับ STRONG" },
        ["instincts.export"] = new() { ["en"] = "Export", ["th"] = "ส่งออก" },
        ["instincts.import"] = new() { ["en"] = "Import", ["th"] = "นำเข้า" },
        ["instincts.storeFolder"] = new() { ["en"] = "Store folder", ["th"] = "โฟลเดอร์จัดเก็บ" },
        ["instincts.refresh"] = new() { ["en"] = "Refresh", ["th"] = "รีเฟรช" },
        ["instincts.pickHint"] = new() { ["en"] = "Pick an instinct on the left, or add a new one below", ["th"] = "เลือกรายการทางซ้าย หรือเพิ่มรายการใหม่ด้านล่าง" },
        ["instincts.confidence"] = new() { ["en"] = "CONFIDENCE", ["th"] = "ความมั่นใจ" },
        ["instincts.when"] = new() { ["en"] = "WHEN (trigger)", ["th"] = "เมื่อ (ตัวกระตุ้น)" },
        ["instincts.do"] = new() { ["en"] = "DO (action / preference)", ["th"] = "ให้ทำ (การกระทำ / ความชอบ)" },
        ["instincts.accept"] = new() { ["en"] = "Accept (it's a real pattern)", ["th"] = "ยอมรับ (เป็นรูปแบบจริง)" },
        ["instincts.reject"] = new() { ["en"] = "Reject (one-off)", ["th"] = "ปฏิเสธ (เกิดครั้งเดียว)" },
        ["instincts.promote"] = new() { ["en"] = "Promote → Skill", ["th"] = "เลื่อนขั้นเป็น Skill" },
        ["instincts.syncOneTip"] = new() { ["en"] = "Push this instinct to ObsidianX as a coding-lesson note (syncs across machines)", ["th"] = "ส่งข้อนี้ไป ObsidianX เป็นโน้ตบทเรียน (ซิงก์ข้ามเครื่อง)" },
        ["instincts.syncToBrain"] = new() { ["en"] = "Sync to brain", ["th"] = "ซิงก์เข้าสมอง" },
        ["instincts.delete"] = new() { ["en"] = "Delete", ["th"] = "ลบ" },
        ["instincts.addManual"] = new() { ["en"] = "ADD A NEW INSTINCT MANUALLY", ["th"] = "เพิ่มรายการใหม่ด้วยตนเอง" },
        ["instincts.patternTip"] = new() { ["en"] = "One-line summary of the pattern", ["th"] = "สรุปรูปแบบสั้นๆ หนึ่งบรรทัด" },
        ["instincts.triggerTip"] = new() { ["en"] = "When this happens...", ["th"] = "เมื่อเกิดเหตุการณ์นี้…" },
        ["instincts.actionTip"] = new() { ["en"] = "...do this", ["th"] = "…ให้ทำแบบนี้" },
        ["instincts.tagsTip"] = new() { ["en"] = "Comma-separated tags (e.g. git, style, perf)", ["th"] = "แท็กคั่นด้วยจุลภาค (เช่น git, style, perf)" },
        ["instincts.addInstinct"] = new() { ["en"] = "Add instinct", ["th"] = "เพิ่มรายการ" },
        ["models.managerTitle"] = new() { ["en"] = "Model Manager", ["th"] = "จัดการโมเดล" },
        ["models.managerSubtitle"] = new() { ["en"] = "Download, browse, and load AI models for local inference", ["th"] = "ดาวน์โหลด ค้นหา และโหลดโมเดล AI สำหรับรันในเครื่อง" },
        ["models.openFolderTip"] = new() { ["en"] = "Open model folder", ["th"] = "เปิดโฟลเดอร์โมเดล" },
        ["models.loadGgufFile"] = new() { ["en"] = "Load GGUF File", ["th"] = "โหลดไฟล์ GGUF" },
        ["models.gpuStatus"] = new() { ["en"] = "GPU Status", ["th"] = "สถานะ GPU" },
        ["models.cancel"] = new() { ["en"] = "Cancel", ["th"] = "ยกเลิก" },
        ["models.tabRecommended"] = new() { ["en"] = "Recommended", ["th"] = "แนะนำ" },
        ["models.tabMyModels"] = new() { ["en"] = "My Models", ["th"] = "โมเดลของฉัน" },
        ["models.tabSearchHf"] = new() { ["en"] = "Search HuggingFace", ["th"] = "ค้นหา HuggingFace" },
        ["models.tabWhereToGet"] = new() { ["en"] = "Where to Get Models", ["th"] = "หาโมเดลได้ที่ไหน" },
        ["models.popularForGpu"] = new() { ["en"] = "Popular Models for Your GPU", ["th"] = "โมเดลยอดนิยมสำหรับการ์ดจอของคุณ" },
        ["models.listView"] = new() { ["en"] = "List view", ["th"] = "มุมมองรายการ" },
        ["models.gridView"] = new() { ["en"] = "Grid view", ["th"] = "มุมมองตาราง" },
        ["models.category"] = new() { ["en"] = "Category:", ["th"] = "หมวด:" },
        ["models.installed"] = new() { ["en"] = "Installed", ["th"] = "ติดตั้งแล้ว" },
        ["models.applyFit"] = new() { ["en"] = "Apply fit", ["th"] = "ใช้ค่าที่แนะนำ" },
        ["models.viewOnHf"] = new() { ["en"] = "View on HuggingFace", ["th"] = "ดูบน HuggingFace" },
        ["models.load"] = new() { ["en"] = "Load", ["th"] = "โหลด" },
        ["models.noMatchVram"] = new() { ["en"] = "No models match this category for your GPU VRAM.", ["th"] = "ไม่มีโมเดลในหมวดนี้ที่เหมาะกับ VRAM ของคุณ" },
        ["models.downloadedModels"] = new() { ["en"] = "Downloaded Models", ["th"] = "โมเดลที่ดาวน์โหลดแล้ว" },
        ["models.scanFolderTip"] = new() { ["en"] = "Scan another folder for GGUF files", ["th"] = "สแกนหาไฟล์ GGUF ในโฟลเดอร์อื่น" },
        ["models.addFolder"] = new() { ["en"] = "Add Folder", ["th"] = "เพิ่มโฟลเดอร์" },
        ["models.unload"] = new() { ["en"] = "Unload", ["th"] = "เอาออกจากหน่วยความจำ" },
        ["models.refresh"] = new() { ["en"] = "Refresh", ["th"] = "รีเฟรช" },
        ["models.deleteTip"] = new() { ["en"] = "Delete model", ["th"] = "ลบโมเดล" },
        ["models.noModelsFound"] = new() { ["en"] = "No models found", ["th"] = "ไม่พบโมเดล" },
        ["models.browseGguf"] = new() { ["en"] = "Browse for GGUF File", ["th"] = "เลือกไฟล์ GGUF" },
        ["models.addModelFolder"] = new() { ["en"] = "Add Model Folder", ["th"] = "เพิ่มโฟลเดอร์โมเดล" },
        ["models.searchHfTitle"] = new() { ["en"] = "Search HuggingFace for GGUF Models", ["th"] = "ค้นหาโมเดล GGUF บน HuggingFace" },
        ["models.search"] = new() { ["en"] = "Search", ["th"] = "ค้นหา" },
        ["models.searching"] = new() { ["en"] = "Searching HuggingFace...", ["th"] = "กำลังค้นหาบน HuggingFace…" },
        ["models.openCardTip"] = new() { ["en"] = "Open model card on HuggingFace", ["th"] = "เปิดหน้าโมเดลบน HuggingFace" },
        ["models.readMore"] = new() { ["en"] = "Read more", ["th"] = "อ่านเพิ่มเติม" },
        ["models.whereToGetTitle"] = new() { ["en"] = "Where to Get GGUF Models", ["th"] = "หาโมเดล GGUF ได้ที่ไหน" },
        ["models.tipsTitle"] = new() { ["en"] = "Tips for Choosing Models", ["th"] = "เคล็ดลับการเลือกโมเดล" },

        // ── auto-wired page strings ──
        ["hex.title"] = new() { ["en"] = "Hex Editor", ["th"] = "Hex Editor" },
        ["hex.subtitle"] = new() { ["en"] = "Binary file viewer + AI-driven patcher", ["th"] = "ดูและแก้ไฟล์ไบนารีด้วย AI" },
        ["hex.open"] = new() { ["en"] = "Open", ["th"] = "เปิด" },
        ["hex.save"] = new() { ["en"] = "Save", ["th"] = "บันทึก" },
        ["hex.saveAs"] = new() { ["en"] = "Save As", ["th"] = "บันทึกเป็น" },
        ["hex.undoTip"] = new() { ["en"] = "Undo (Ctrl+Z)", ["th"] = "เลิกทำ (Ctrl+Z)" },
        ["hex.undo"] = new() { ["en"] = "Undo", ["th"] = "เลิกทำ" },
        ["hex.redoTip"] = new() { ["en"] = "Redo (Ctrl+Y)", ["th"] = "ทำซ้ำ (Ctrl+Y)" },
        ["hex.redo"] = new() { ["en"] = "Redo", ["th"] = "ทำซ้ำ" },
        ["hex.findTip"] = new() { ["en"] = "Find / Replace (Ctrl+F)", ["th"] = "ค้นหา / แทนที่ (Ctrl+F)" },
        ["hex.find"] = new() { ["en"] = "Find", ["th"] = "ค้นหา" },
        ["hex.gotoTip"] = new() { ["en"] = "Go to offset (e.g. 0x1A00 or 6656)", ["th"] = "ไปที่ offset (เช่น 0x1A00 หรือ 6656)" },
        ["hex.inspectorBtn"] = new() { ["en"] = "Inspector", ["th"] = "ตัวตรวจค่า" },
        ["hex.patternTip"] = new() { ["en"] = "Pattern to find", ["th"] = "รูปแบบที่ต้องการค้นหา" },
        ["hex.findAll"] = new() { ["en"] = "Find All", ["th"] = "ค้นหาทั้งหมด" },
        ["hex.replaceWith"] = new() { ["en"] = "Replace with:", ["th"] = "แทนที่ด้วย:" },
        ["hex.replaceTip"] = new() { ["en"] = "Replacement bytes (same length)", ["th"] = "ไบต์ที่จะแทนที่ (ความยาวเท่าเดิม)" },
        ["hex.replaceAll"] = new() { ["en"] = "Replace All", ["th"] = "แทนที่ทั้งหมด" },
        ["hex.offset"] = new() { ["en"] = "OFFSET", ["th"] = "ตำแหน่ง" },
        ["hex.prevPage"] = new() { ["en"] = "◀ Prev page", ["th"] = "◀ หน้าก่อน" },
        ["hex.nextPage"] = new() { ["en"] = "Next page ▶", ["th"] = "หน้าถัดไป ▶" },
        ["hex.copyHex"] = new() { ["en"] = "Copy hex", ["th"] = "คัดลอก hex" },
        ["hex.copyAscii"] = new() { ["en"] = "Copy ASCII", ["th"] = "คัดลอก ASCII" },
        ["hex.inspector"] = new() { ["en"] = "INSPECTOR", ["th"] = "ตัวตรวจค่า" },
        ["hex.patchAtSelection"] = new() { ["en"] = "PATCH AT SELECTION", ["th"] = "แก้ไบต์ที่เลือก" },
        ["hex.patchTip"] = new() { ["en"] = "Bytes to write (hex). Same length as current selection — does not extend file.", ["th"] = "ไบต์ที่จะเขียน (hex) ความยาวเท่าที่เลือก — ไม่ขยายขนาดไฟล์" },
        ["hex.applyPatch"] = new() { ["en"] = "Apply patch", ["th"] = "เขียนทับ" },
        ["hex.searchResults"] = new() { ["en"] = "SEARCH RESULTS", ["th"] = "ผลการค้นหา" },
        ["nav.versionTip"] = new() { ["en"] = "Version · commit · build time of this running binary", ["th"] = "เวอร์ชัน · คอมมิต · เวลาที่บิลด์ของไฟล์ที่รันอยู่" },
        ["nav.noProject"] = new() { ["en"] = "(no project open)", ["th"] = "(ยังไม่ได้เปิดโปรเจค)" },
        ["nav.searchPlaceholder"] = new() { ["en"] = "Search files, symbols &amp; commands…", ["th"] = "ค้นหาไฟล์ สัญลักษณ์ และคำสั่ง…" },
        ["nav.newChatTip"] = new() { ["en"] = "New Chat (Ctrl+N)", ["th"] = "แชทใหม่ (Ctrl+N)" },
        ["nav.checkUpdatesTip"] = new() { ["en"] = "Check for updates", ["th"] = "ตรวจหาอัปเดต" },
        ["nav.chatTip"] = new() { ["en"] = "Chat (Ctrl+1)", ["th"] = "แชท (Ctrl+1)" },
        ["nav.codeTip"] = new() { ["en"] = "Code Editor (Ctrl+5)", ["th"] = "อีดิเตอร์โค้ด (Ctrl+5)" },
        ["nav.subagentsTip"] = new() { ["en"] = "Subagents (Ctrl+6)", ["th"] = "Subagent (Ctrl+6)" },
        ["nav.skillsTip"] = new() { ["en"] = "Skills (Ctrl+7)", ["th"] = "Skill (Ctrl+7)" },
        ["nav.instinctsTip"] = new() { ["en"] = "Instincts (Ctrl+8) — continuous learning", ["th"] = "สัญชาตญาณ (Ctrl+8) — เรียนรู้ต่อเนื่อง" },
        ["nav.debugLogTip"] = new() { ["en"] = "Debug Log (Ctrl+9) — dev diagnostics", ["th"] = "บันทึกดีบัก (Ctrl+9) — สำหรับนักพัฒนา" },
        ["nav.shieldTip"] = new() { ["en"] = "SecurityShield — OWASP-style scanner (51 rules)", ["th"] = "SecurityShield — สแกนความปลอดภัยสไตล์ OWASP (51 กฎ)" },
        ["nav.hooksTip"] = new() { ["en"] = "Hook Library — 16 bundled .ps1 hooks (PreToolUse/PostToolUse/Stop/SessionStart/PreCompact)", ["th"] = "คลังฮุก — สคริปต์ .ps1 พร้อมใช้ 16 ตัว (PreToolUse/PostToolUse/Stop/SessionStart/PreCompact)" },
        ["nav.modelsTip"] = new() { ["en"] = "Models (Ctrl+2)", ["th"] = "โมเดล (Ctrl+2)" },
        ["nav.timeMachineTip"] = new() { ["en"] = "Time Machine (Ctrl+3)", ["th"] = "ย้อนเวลา (Ctrl+3)" },
        ["nav.hexTip"] = new() { ["en"] = "Hex Editor (Ctrl+4)", ["th"] = "Hex Editor (Ctrl+4)" },
        ["nav.pluginsTip"] = new() { ["en"] = "Plugins", ["th"] = "ปลั๊กอิน" },
        ["nav.mcpTip"] = new() { ["en"] = "MCP Servers", ["th"] = "เซิร์ฟเวอร์ MCP" },
        ["nav.tasksTip"] = new() { ["en"] = "Tasks", ["th"] = "งาน" },
        ["nav.permissionsTip"] = new() { ["en"] = "Permissions", ["th"] = "สิทธิ์การเข้าถึง" },
        ["nav.featuresTip"] = new() { ["en"] = "Features", ["th"] = "ฟีเจอร์" },
        ["nav.settingsTip"] = new() { ["en"] = "Settings (Ctrl+,)", ["th"] = "ตั้งค่า (Ctrl+,)" },
        ["nav.allProjectsTip"] = new() { ["en"] = "Show sessions from all projects", ["th"] = "แสดงเซสชันจากทุกโปรเจค" },
        ["nav.installRestart"] = new() { ["en"] = "Install &amp; Restart", ["th"] = "ติดตั้งแล้วเริ่มใหม่" },
        ["nav.dismissTip"] = new() { ["en"] = "Dismiss", ["th"] = "ปิดข้อความ" },
        ["nav.gpuMonitor"] = new() { ["en"] = "GPU live monitor", ["th"] = "ติดตาม GPU แบบเรียลไทม์" },
        ["nav.utilization"] = new() { ["en"] = "Utilization: ", ["th"] = "การใช้งาน:" },
        ["nav.temperature"] = new() { ["en"] = "Temperature: ", ["th"] = "อุณหภูมิ:" },
        ["nav.bridge"] = new() { ["en"] = "ObsidianX bridge (MCP host)", ["th"] = "สะพาน ObsidianX (MCP host)" },
        ["nav.secure"] = new() { ["en"] = "SECURE · 0 telemetry", ["th"] = "ปลอดภัย · ไม่ส่งข้อมูลออก" },
        ["nav.loadingModel"] = new() { ["en"] = "Loading Model", ["th"] = "กำลังโหลดโมเดล" },
        ["nav.loadingHint"] = new() { ["en"] = "Please wait while the model loads into memory...", ["th"] = "โปรดรอสักครู่ ระบบกำลังโหลดโมเดลเข้าหน่วยความจำ…" },

        // ── auto-wired page strings ──
        ["chat.agentTip"] = new() { ["en"] = "Enable agentic mode (file access, commands, Git)", ["th"] = "เปิดโหมดเอเจนต์ (เข้าถึงไฟล์ รันคำสั่ง ใช้ Git)" },
        ["chat.auto"] = new() { ["en"] = "Auto", ["th"] = "อัตโนมัติ" },
        ["chat.autoTip"] = new() { ["en"] = "Autonomous mode: implement → run the project's tests → fix → loop until green, then review for hidden bugs. Set iteration counts in Settings.", ["th"] = "โหมดอัตโนมัติ: เขียนโค้ด → รันเทสต์ → แก้ → วนจนผ่าน แล้วตรวจหาบั๊กที่ซ่อนอยู่ ตั้งจำนวนรอบได้ในหน้าตั้งค่า" },
        ["chat.thinkingToggle"] = new() { ["en"] = "Thinking", ["th"] = "การคิด" },
        ["chat.thinkingTip"] = new() { ["en"] = "Show AI thinking/reasoning steps in real-time", ["th"] = "แสดงขั้นตอนการคิดของ AI แบบเรียลไทม์" },
        ["chat.closeProjectTip"] = new() { ["en"] = "Close project folder", ["th"] = "ปิดโฟลเดอร์โปรเจค" },
        ["chat.closeSearchTip"] = new() { ["en"] = "Close search (Esc)", ["th"] = "ปิดการค้นหา (Esc)" },
        ["chat.allow"] = new() { ["en"] = "Allow", ["th"] = "อนุญาต" },
        ["chat.deny"] = new() { ["en"] = "Deny", ["th"] = "ปฏิเสธ" },
        ["chat.interrupted"] = new() { ["en"] = "interrupted", ["th"] = "ถูกขัดจังหวะ" },
        ["chat.copyMessageTip"] = new() { ["en"] = "Copy message", ["th"] = "คัดลอกข้อความ" },
        ["chat.retryTip"] = new() { ["en"] = "Retry", ["th"] = "ลองใหม่" },
        ["chat.changes"] = new() { ["en"] = "Changes", ["th"] = "การเปลี่ยนแปลง" },
        ["chat.showOutput"] = new() { ["en"] = "Show output", ["th"] = "ดูผลลัพธ์" },
        ["chat.welcomeTitle"] = new() { ["en"] = "CluadeX AI Coding Assistant", ["th"] = "CluadeX ผู้ช่วยเขียนโค้ด AI" },
        ["chat.welcomeSubtitle"] = new() { ["en"] = "Ask me to write, debug, or explain any code.", ["th"] = "สั่งให้เขียน แก้บั๊ก หรืออธิบายโค้ดอะไรก็ได้" },
        ["chat.suggestExplain"] = new() { ["en"] = "Explain codebase", ["th"] = "อธิบายโค้ดเบส" },
        ["chat.suggestBugs"] = new() { ["en"] = "Find bugs", ["th"] = "หาบั๊ก" },
        ["chat.suggestTests"] = new() { ["en"] = "Write tests", ["th"] = "เขียนเทสต์" },
        ["chat.suggestReview"] = new() { ["en"] = "Code review", ["th"] = "รีวิวโค้ด" },
        ["chat.openProjectFolder"] = new() { ["en"] = "Open Project Folder", ["th"] = "เปิดโฟลเดอร์โปรเจค" },
        ["chat.connectRepo"] = new() { ["en"] = "Connect GitHub repo", ["th"] = "เชื่อม repo GitHub" },
        ["chat.openHint"] = new() { ["en"] = "Open a folder or clone a repo to enable agent mode (file access, editing, Git)", ["th"] = "เปิดโฟลเดอร์หรือโคลน repo เพื่อเปิดโหมดเอเจนต์ (เข้าถึงไฟล์ แก้ไข ใช้ Git)" },
        ["chat.openProjectTip"] = new() { ["en"] = "Open project folder", ["th"] = "เปิดโฟลเดอร์โปรเจค" },
        ["chat.clearChatTip"] = new() { ["en"] = "Clear chat", ["th"] = "ล้างแชท" },
        ["chat.compactNowTip"] = new() { ["en"] = "Compact the conversation now", ["th"] = "บีบอัดบทสนทนาตอนนี้" },
        ["chat.compactNow"] = new() { ["en"] = "Compact now", ["th"] = "บีบอัดตอนนี้" },
        ["chat.snoozeTip"] = new() { ["en"] = "Don't ask for 10 more turns", ["th"] = "อย่าถามอีก 10 ตา" },
        ["chat.snooze"] = new() { ["en"] = "Snooze 10 turns", ["th"] = "เลื่อนไป 10 ตา" },
        ["chat.dismissTip"] = new() { ["en"] = "Dismiss", ["th"] = "ปิดข้อความ" },
        ["chat.compactTip"] = new() { ["en"] = "Compress conversation to free up context", ["th"] = "บีบอัดบทสนทนาเพื่อคืนพื้นที่ context" },
        ["chat.compact"] = new() { ["en"] = "Compact", ["th"] = "บีบอัด" },
        ["chat.newChatTip"] = new() { ["en"] = "Start a new chat to reset context", ["th"] = "เริ่มแชทใหม่เพื่อล้าง context" },
        ["chat.newChat"] = new() { ["en"] = "New Chat", ["th"] = "แชทใหม่" },
        ["chat.selectModelTip"] = new() { ["en"] = "Select a local model to load", ["th"] = "เลือกโมเดลในเครื่องเพื่อโหลด" },
        ["chat.refreshModelsTip"] = new() { ["en"] = "Refresh model list", ["th"] = "รีเฟรชรายชื่อโมเดล" },
        ["chat.loading"] = new() { ["en"] = "Loading...", ["th"] = "กำลังโหลด…" },
        ["chat.generating"] = new() { ["en"] = "Generating...", ["th"] = "กำลังสร้างคำตอบ…" },
        ["chat.ctxTip"] = new() { ["en"] = "Context Memory — AI quality degrades as this fills up", ["th"] = "หน่วยความจำ context — ยิ่งเต็ม คุณภาพคำตอบยิ่งลด" },
        ["chat.lastTurnTip"] = new() { ["en"] = "Last turn: tokens · time · speed", ["th"] = "ตาล่าสุด: โทเค็น · เวลา · ความเร็ว" },
        ["chat.costTip"] = new() { ["en"] = "Session API cost (USD)", ["th"] = "ค่าใช้จ่าย API ของเซสชันนี้ (USD)" },
        ["chat.reviewTip"] = new() { ["en"] = "Review code changes", ["th"] = "รีวิวการเปลี่ยนแปลงโค้ด" },
        ["chat.autoRunTip"] = new() { ["en"] = "Automatically run code blocks and fix errors", ["th"] = "รันบล็อกโค้ดและแก้ error อัตโนมัติ" },
        ["chat.extendedThinkingTip"] = new() { ["en"] = "Extended Thinking — enables deeper reasoning (Anthropic only)", ["th"] = "Extended Thinking — คิดลึกขึ้น (เฉพาะ Anthropic)" },
        ["chat.think"] = new() { ["en"] = "Think", ["th"] = "คิด" },

        // ── auto-wired page strings ──
        ["settings.browseTip"] = new() { ["en"] = "Browse", ["th"] = "เลือกโฟลเดอร์" },
        ["settings.openFolderTip"] = new() { ["en"] = "Open folder", ["th"] = "เปิดโฟลเดอร์" },
        ["settings.sessionFolder"] = new() { ["en"] = "Session folder", ["th"] = "โฟลเดอร์เซสชัน" },
        ["settings.sessionFolderDesc"] = new() { ["en"] = "Where chat sessions are stored. Empty = the default under your user profile.", ["th"] = "ที่เก็บเซสชันแชท เว้นว่าง = ใช้ค่าเริ่มต้นใต้โปรไฟล์ผู้ใช้" },
        ["settings.thinkingDesc"] = new() { ["en"] = "Enable Claude's extended thinking mode for complex reasoning. Uses additional tokens for internal reasoning before responding.", ["th"] = "เปิดโหมดคิดลึกของ Claude สำหรับงานที่ซับซ้อน ใช้โทเค็นเพิ่มเพื่อคิดก่อนตอบ" },
        ["settings.cachingDesc"] = new() { ["en"] = "Cache the system prompt across API calls to reduce costs. Recommended for Anthropic.", ["th"] = "แคช system prompt ข้ามการเรียก API เพื่อลดค่าใช้จ่าย แนะนำสำหรับ Anthropic" },
        ["settings.agentBehaviour"] = new() { ["en"] = "Agent Behaviour", ["th"] = "พฤติกรรมของเอเจนต์" },
        ["settings.maxSteps"] = new() { ["en"] = "Max agent steps per turn:", ["th"] = "จำนวนขั้นสูงสุดต่อหนึ่งตา:" },
        ["settings.maxStepsTip"] = new() { ["en"] = "How many tool-use steps the agent may take before it must answer. Higher = can finish longer tasks, but costs more.", ["th"] = "เอเจนต์เรียกเครื่องมือได้กี่ครั้งก่อนต้องตอบ ยิ่งมากยิ่งทำงานยาวได้ แต่ค่าใช้จ่ายสูงขึ้น" },
        ["settings.idleTimeout"] = new() { ["en"] = "Idle timeout (seconds, 0 = none):", ["th"] = "หมดเวลารอ (วินาที, 0 = ไม่จำกัด):" },
        ["settings.idleTimeoutTip"] = new() { ["en"] = "Abort a request that produces NO output for this long. Resets on every streamed token.", ["th"] = "ยกเลิกคำขอที่ไม่มีผลลัพธ์ออกมาเลยนานเท่านี้ นับใหม่ทุกครั้งที่มีโทเค็นไหลออก" },
        ["settings.readBeforeEdit"] = new() { ["en"] = "Require reading a file before editing it", ["th"] = "ต้องอ่านไฟล์ก่อนจึงจะแก้ได้" },
        ["settings.readBeforeEditDesc"] = new() { ["en"] = "Blocks blind edits and edits to files that changed on disk since the last read (Claude Code behaviour).", ["th"] = "กันการแก้แบบไม่ได้อ่าน และกันการแก้ไฟล์ที่เปลี่ยนบนดิสก์หลังอ่านครั้งล่าสุด (แบบเดียวกับ Claude Code)" },
        ["settings.autoVerify"] = new() { ["en"] = "Build automatically after an edit and feed errors back", ["th"] = "บิลด์อัตโนมัติหลังแก้ไข แล้วส่ง error กลับให้ AI" },
        ["settings.autoVerifyDesc"] = new() { ["en"] = "Turns the compiler into the agent's oracle — it sees its own mistakes instead of claiming success.", ["th"] = "ให้คอมไพเลอร์เป็นตัวตัดสิน — AI เห็นความผิดพลาดของตัวเองแทนที่จะอ้างว่าสำเร็จ" },
        ["settings.planFirst"] = new() { ["en"] = "Plan first, then force a tool call", ["th"] = "วางแผนก่อน แล้วบังคับให้เรียกเครื่องมือ" },
        ["settings.midLoopReminder"] = new() { ["en"] = "Remind the agent of the goal mid-loop", ["th"] = "เตือนเป้าหมายกลางลูป" },
        ["settings.remindEvery"] = new() { ["en"] = "Remind every N steps:", ["th"] = "เตือนทุกกี่ขั้น:" },
        ["settings.escalate"] = new() { ["en"] = "Escalate to a stronger provider when the local model stalls", ["th"] = "ส่งต่อให้ provider ที่เก่งกว่าเมื่อโมเดลในเครื่องไปต่อไม่ได้" },
        ["settings.escalateTo"] = new() { ["en"] = "Escalate to provider:", ["th"] = "ส่งต่อไปยัง provider:" },
        ["settings.escalateToTip"] = new() { ["en"] = "Provider id to hand off to, e.g. Anthropic. Empty = the first configured API provider.", ["th"] = "ชื่อ provider ที่จะส่งต่อ เช่น Anthropic เว้นว่าง = ใช้ตัวแรกที่ตั้งค่าไว้" },
        ["settings.learnInstincts"] = new() { ["en"] = "Learn instincts from finished sessions", ["th"] = "เรียนรู้สัญชาตญาณจากเซสชันที่จบแล้ว" },
        ["settings.brainRecall"] = new() { ["en"] = "Auto-recall from BrainX before answering", ["th"] = "ดึงความรู้จาก BrainX ก่อนตอบอัตโนมัติ" },
        ["settings.semanticSearch"] = new() { ["en"] = "Semantic (embedding) codebase search", ["th"] = "ค้นหาโค้ดเชิงความหมาย (embedding)" },
        ["settings.embeddingModel"] = new() { ["en"] = "Embedding model:", ["th"] = "โมเดล embedding:" },
        ["settings.embeddingModelTip"] = new() { ["en"] = "Ollama embedding model used for semantic search, e.g. nomic-embed-text.", ["th"] = "โมเดล embedding ของ Ollama ที่ใช้ค้นหาเชิงความหมาย เช่น nomic-embed-text" },
        ["settings.microKeep"] = new() { ["en"] = "Microcompact — keep last N turns:", ["th"] = "Microcompact — เก็บกี่ตาล่าสุด:" },
        ["settings.microTruncate"] = new() { ["en"] = "Truncate older tool results to (chars):", ["th"] = "ตัดผลเครื่องมือเก่าเหลือ (ตัวอักษร):" },
        ["settings.localModelSection"] = new() { ["en"] = "Local Model — Tool Calling &amp; Sampling", ["th"] = "โมเดลในเครื่อง — การเรียกเครื่องมือและการสุ่ม" },
        ["settings.nativeToolUse"] = new() { ["en"] = "Native tool calling for local models (llama-server / Ollama)", ["th"] = "เรียกเครื่องมือแบบ native สำหรับโมเดลในเครื่อง (llama-server / Ollama)" },
        ["settings.nativeToolUseDesc"] = new() { ["en"] = "Uses structured function-calling instead of the [ACTION:] text protocol. Much more reliable — turn OFF only if your model has no tool template.", ["th"] = "ใช้ function-calling แบบมีโครงสร้างแทนโปรโตคอลข้อความ [ACTION:] เสถียรกว่ามาก — ปิดเฉพาะเมื่อโมเดลไม่มี tool template" },
        ["settings.toolRepair"] = new() { ["en"] = "Repair tool calls a weak model wrote as prose", ["th"] = "กู้คืนการเรียกเครื่องมือที่โมเดลอ่อนพิมพ์เป็นข้อความธรรมดา" },
        ["settings.toolRepairDesc"] = new() { ["en"] = "Recovers a call the model typed into its reply instead of emitting properly. Rescues most weak-model dead-ends.", ["th"] = "กู้การเรียกที่โมเดลพิมพ์ลงในคำตอบแทนที่จะส่งออกมาให้ถูกต้อง ช่วยแก้ทางตันของโมเดลอ่อนได้เกือบทั้งหมด" },
        ["settings.zeroDisabled"] = new() { ["en"] = "0 = disabled", ["th"] = "0 = ปิดใช้" },
        ["settings.repeatWindow"] = new() { ["en"] = "Repeat window:", ["th"] = "ช่วงตรวจซ้ำ:" },
        ["settings.repeatWindowTip"] = new() { ["en"] = "How many recent tokens the repeat penalty considers.", ["th"] = "บทลงโทษการซ้ำจะพิจารณาโทเค็นล่าสุดกี่ตัว" },
        ["settings.toolCallTemp"] = new() { ["en"] = "Tool-call temp:", ["th"] = "temp ตอนเรียกเครื่องมือ:" },
        ["settings.toolCallTempTip"] = new() { ["en"] = "Lower temperature used specifically for tool-calling steps (more deterministic arguments).", ["th"] = "ใช้ temperature ต่ำเฉพาะตอนเรียกเครื่องมือ เพื่อให้อาร์กิวเมนต์แน่นอนขึ้น" },
        ["settings.customBackend"] = new() { ["en"] = "Custom llama.cpp backend folder:", ["th"] = "โฟลเดอร์ backend llama.cpp ของคุณเอง:" },
        ["settings.customBackendTip"] = new() { ["en"] = "Folder containing your own llama-server build. Empty = use the bundled backend.", ["th"] = "โฟลเดอร์ที่มี llama-server ที่คุณบิลด์เอง เว้นว่าง = ใช้ตัวที่มากับโปรแกรม" },
        ["settings.autoLoopSection"] = new() { ["en"] = "Autonomous Loop (drive to green)", ["th"] = "ลูปอัตโนมัติ (ทำจนผ่าน)" },
        ["settings.autoLoopEnable"] = new() { ["en"] = "Enable autonomous mode (implement → run tests → fix → loop, then review)", ["th"] = "เปิดโหมดอัตโนมัติ (เขียน → รันเทสต์ → แก้ → วน แล้วรีวิว)" },
        ["settings.autoLoopDesc"] = new() { ["en"] = "Edits files, runs the project's build/tests on your machine, reads the failures, and loops back to fix — until it passes. Every loop is capped to avoid runaway cost.", ["th"] = "แก้ไฟล์ รันบิลด์/เทสต์บนเครื่องคุณ อ่าน error แล้ววนกลับไปแก้จนผ่าน ทุกลูปมีเพดานกันค่าใช้จ่ายบานปลาย" },
        ["settings.maxFixIterations"] = new() { ["en"] = "Max fix iterations:", ["th"] = "จำนวนรอบแก้สูงสุด:" },
        ["settings.verifyCommand"] = new() { ["en"] = "Verify command (empty = auto-detect):", ["th"] = "คำสั่งตรวจสอบ (เว้นว่าง = ตรวจอัตโนมัติ):" },
        ["settings.verifyCommandTip"] = new() { ["en"] = "e.g. dotnet build / npm test / pytest. Empty = auto-detect from project files.", ["th"] = "เช่น dotnet build / npm test / pytest เว้นว่าง = ตรวจจากไฟล์โปรเจคอัตโนมัติ" },
        ["settings.reviewAfterGreen"] = new() { ["en"] = "Review for hidden bugs after the build is green", ["th"] = "ตรวจหาบั๊กที่ซ่อนอยู่หลังบิลด์ผ่าน" },
        ["settings.reviewMode"] = new() { ["en"] = "Review mode:", ["th"] = "โหมดรีวิว:" },
        ["settings.reviewUntilClean"] = new() { ["en"] = "Until clean", ["th"] = "จนกว่าจะไม่เจอ" },
        ["settings.reviewFixedRounds"] = new() { ["en"] = "Fixed rounds", ["th"] = "จำนวนรอบคงที่" },
        ["settings.maxReviewRounds"] = new() { ["en"] = "Max review rounds:", ["th"] = "จำนวนรอบรีวิวสูงสุด:" },
        ["settings.autoExecuteDesc"] = new() { ["en"] = "When enabled, CluadeX will automatically run generated code and fix errors.", ["th"] = "เมื่อเปิด CluadeX จะรันโค้ดที่สร้างขึ้นและแก้ error ให้อัตโนมัติ" },
        ["settings.maxAutoFix"] = new() { ["en"] = "Max Auto-Fix Attempts:", ["th"] = "จำนวนครั้งแก้อัตโนมัติสูงสุด:" },
        ["settings.preferredLanguage"] = new() { ["en"] = "Preferred Language:", ["th"] = "ภาษาโปรแกรมที่ถนัด:" },
        ["settings.streamOutput"] = new() { ["en"] = "Stream Output (show tokens as they generate)", ["th"] = "สตรีมผลลัพธ์ (แสดงโทเค็นระหว่างสร้าง)" },
        ["settings.apiTokenOptional"] = new() { ["en"] = "API Token (optional)", ["th"] = "API Token (ไม่บังคับ)" },
        ["settings.apiTokenDesc"] = new() { ["en"] = "Required only for private or gated models. Get your token from huggingface.co/settings/tokens", ["th"] = "จำเป็นเฉพาะโมเดลส่วนตัวหรือที่ต้องขอสิทธิ์ ขอ token ได้ที่ huggingface.co/settings/tokens" },
        ["settings.memoriesDesc"] = new() { ["en"] = "Persistent memories saved by the AI agent. These survive across chat sessions.", ["th"] = "ความทรงจำถาวรที่ AI บันทึกไว้ คงอยู่ข้ามเซสชันแชท" },
        ["settings.saveSettings"] = new() { ["en"] = "💾 Save Settings", ["th"] = "💾 บันทึกการตั้งค่า" },

        // ── auto-wired page strings ──
        ["hooks.bundledCount"] = new() { ["en"] = "16 bundled .ps1 hooks · ", ["th"] = "สคริปต์ .ps1 พร้อมใช้ 16 ตัว ·" },
        ["hooks.enabledSuffix"] = new() { ["en"] = " enabled", ["th"] = " เปิดใช้อยู่" },
        ["hooks.matcherLabel"] = new() { ["en"] = "matcher: ", ["th"] = "ตัวจับคู่:" },
        ["hooks.timeoutLabel"] = new() { ["en"] = "   timeout: ", ["th"] = "   หมดเวลา:" },
        ["shield.staticAnalysis"] = new() { ["en"] = "Static analysis · ", ["th"] = "วิเคราะห์แบบสถิต ·" },
        ["shield.rulesSuffix"] = new() { ["en"] = " rules · ", ["th"] = " กฎ ·" },
        ["shield.filesSuffix"] = new() { ["en"] = " files · ", ["th"] = " ไฟล์ ·" },
        ["shield.clickPrefix"] = new() { ["en"] = "Click ", ["th"] = "กด" },
        ["shield.toRun"] = new() { ["en"] = " to run ", ["th"] = " เพื่อสแกนด้วย" },
        ["shield.rulesAcross"] = new() { ["en"] = " rules across your codebase", ["th"] = " กฎทั่วทั้งโค้ดเบสของคุณ" },
        ["shield.lineLabel"] = new() { ["en"] = "line ", ["th"] = "บรรทัด" },
        ["skills.builtInBadge"] = new() { ["en"] = "built-in", ["th"] = "มากับโปรแกรม" },
        ["skills.subtitle"] = new() { ["en"] = "Reusable slash-command prompts · ", ["th"] = "prompt แบบ slash-command ใช้ซ้ำได้ ·" },
        ["skills.builtInSuffix"] = new() { ["en"] = " built-in · ", ["th"] = " ในตัว ·" },
        ["skills.customSuffix"] = new() { ["en"] = " custom", ["th"] = " กำหนดเอง" },
        ["skills.copy"] = new() { ["en"] = "📋 Copy", ["th"] = "📋 คัดลอก" },
        ["subagents.builtInBadge"] = new() { ["en"] = "built-in", ["th"] = "มากับโปรแกรม" },
        ["subagents.subtitle"] = new() { ["en"] = "Specialised single-purpose agents · ", ["th"] = "เอเจนต์เฉพาะทางทำงานเดียว ·" },
        ["subagents.builtInSuffix"] = new() { ["en"] = " built-in · ", ["th"] = " ในตัว ·" },
        ["subagents.customSuffix"] = new() { ["en"] = " custom", ["th"] = " กำหนดเอง" },
        ["subagents.copy"] = new() { ["en"] = "📋 Copy", ["th"] = "📋 คัดลอก" },
        ["instincts.promotedBadge"] = new() { ["en"] = "PROMOTED", ["th"] = "เลื่อนขั้นแล้ว" },
        ["instincts.subtitle"] = new() { ["en"] = "Patterns the agent learned · ", ["th"] = "รูปแบบที่เอเจนต์เรียนรู้ ·" },
        ["instincts.strongSuffix"] = new() { ["en"] = " strong · ", ["th"] = " ชัดเจน ·" },
        ["instincts.emergingSuffix"] = new() { ["en"] = " emerging · ", ["th"] = " กำลังก่อตัว ·" },
        ["instincts.totalSuffix"] = new() { ["en"] = " total", ["th"] = " ทั้งหมด" },
        ["instincts.promotedToSkill"] = new() { ["en"] = "✓ Promoted to skill", ["th"] = "✓ เลื่อนขั้นเป็น skill แล้ว" },
        ["timemachine.filesSuffix"] = new() { ["en"] = " files  ", ["th"] = " ไฟล์" },
        ["timemachine.commitsSuffix"] = new() { ["en"] = " commits", ["th"] = " คอมมิต" },
        ["debuglog.subtitle"] = new() { ["en"] = "In-memory ring buffer · disk rotation daily · ", ["th"] = "บัฟเฟอร์วนในหน่วยความจำ · หมุนไฟล์รายวัน ·" },
        ["debuglog.visibleSuffix"] = new() { ["en"] = " visible · ", ["th"] = " รายการที่แสดง ·" },
        ["models.vramLabel"] = new() { ["en"] = "VRAM: ", ["th"] = "VRAM:" },
        ["models.sizeLabel"] = new() { ["en"] = "  |  Size: ", ["th"] = "  |  ขนาด:" },
        ["mcp.discoveredTools"] = new() { ["en"] = "Discovered Tools (", ["th"] = "เครื่องมือที่พบ (" },
        ["editor.terminalLabel"] = new() { ["en"] = "Terminal", ["th"] = "เทอร์มินัล" },
        ["chat.thinkingInline"] = new() { ["en"] = "  Thinking...", ["th"] = "  กำลังคิด…" },
        ["chat.linesSuffix"] = new() { ["en"] = " lines)", ["th"] = " บรรทัด)" },
        ["chat.errorHover"] = new() { ["en"] = " An error occurred. Hover for retry button.", ["th"] = " เกิดข้อผิดพลาด วางเมาส์เพื่อดูปุ่มลองใหม่" },

        // ── auto-wired page strings ──
        ["nav.paletteTip"] = new() { ["en"] = "Command palette — jump to a page, run a skill, or open a file (Ctrl+K)", ["th"] = "แถบคำสั่ง — ไปหน้าอื่น เรียก skill หรือเปิดไฟล์ (Ctrl+K)" },
        ["nav.paletteHint"] = new() { ["en"] = "↑↓ navigate · Enter run · Esc close", ["th"] = "↑↓ เลื่อน · Enter เรียกใช้ · Esc ปิด" },
    };

    public void SetLanguage(string lang)
    {
        if (lang != "en" && lang != "th") lang = "en";
        _currentLanguage = lang;
        LanguageChanged?.Invoke();
    }

    /// <summary>Get translation for a key. Falls back to English, then to the key itself.</summary>
    public string T(string key)
    {
        if (Translations.TryGetValue(key, out var dict))
        {
            if (dict.TryGetValue(_currentLanguage, out var val))
                return val;
            if (dict.TryGetValue("en", out var fallback))
                return fallback;
        }
        return key;
    }

    /// <summary>Get translation with format args.</summary>
    public string T(string key, params object[] args)
    {
        return string.Format(T(key), args);
    }

    public string[] AvailableLanguages => ["en", "th"];
    public string[] LanguageDisplayNames => ["English", "ไทย"];
}
